# -*- coding: utf-8 -*-
"""merge_csv_file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Ss3MkbMpG7brj3SCBEVD30T0ZS4rOBa
"""

!pip install xlrd
!pip install openpyxl

from google.colab import drive
drive.mount('/content/gdrive/')

import os

# 현재 디렉토리 변경 

os.getcwd()
os.chdir('/content/gdrive/My Drive/Colab Notebooks/text_sum_train_set/')

import pandas as pd

os.getcwd()

os.listdir()

emp1 = pd.read_csv('bbc_newspaper_all (500).csv')
emp2 = pd.read_csv('bbc_newspaper_business(230).csv')
emp3 = pd.read_csv('cnn_newspaper(450).csv', encoding='cp949')
emp4 = pd.read_csv('education_office_dataset.csv', encoding = 'cp949')
emp5 = pd.read_csv('India today(1000).csv')
emp6 = pd.read_csv('India today(2000).csv')
emp7 = pd.read_csv('LA times(0_500).csv')
emp8 = pd.read_csv('LA times(500_1000).csv')
emp9 = pd.read_csv('LA times(1000_2000).csv')
emp10 = pd.read_csv('NY Times(1800).csv')
emp11 = pd.read_excel('CSAT_jaehyung.xlsx')
emp12 = pd.read_excel('CSAT_kanghee.xlsx')

merge_emp = pd.concat([emp1, emp2, emp3, emp4, emp5, emp6, emp7, emp8, emp9, emp10, emp11, emp12], sort = False)

merge_emp.to_excel('merge_train.xlsx', sheet_name = 'Sheet1')

